version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: stonks-app:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "22222:3000" # Host:Container
    # If your NAS needs a specific network, you can add:
    # networks:
    #   - stonks-net

# networks:
#   stonks-net:
#     driver: bridge

