version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: stonks-app:latest
    restart: unless-stopped

    environment:
      DATABASE_URL: "postgresql://user:pass@host.docker.internal:5432/dbname?schema=public"
      NEXT_TELEMETRY_DISABLED: "1"
      PORT: "3000"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - "22222:3000"

